language: generic 
sudo: required
services:
  - docker

before_install: 
  - docker build -t shakzaken/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true shakzaken/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: ""
  app: "docker-react"
  env: ""
  bucket_name: ""
  bucket_path: ""
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"

